local IslandProjectStore = {}
local IslandLayout = require("IslandLayout")
local IslandTerrainCatalog = require("IslandTerrainCatalog")
local IslandPortalNetwork = require("IslandPortalNetwork")
local RandomTerrainGenerator = require("RandomTerrainGenerator")

IslandProjectStore.SCHEMA = "island-collection/v1"

local sequence = 0
local randomSequence = 0
-- Full terrain cards include a live topology preview. Keeping the user library
-- deliberately compact avoids rebuilding dozens of complex cards on phones;
-- referenced imports beyond the creation cap are still recovered below.
local MAX_RANDOM_TERRAINS = 24

local function Copy(value, seen)
    if type(value) ~= "table" then return value end
    seen = seen or {}
    if seen[value] then return seen[value] end
    local result = {}
    seen[value] = result
    for key, item in pairs(value) do result[Copy(key, seen)] = Copy(item, seen) end
    return result
end

-- Proves that two snapshots contain the same values without allocating a
-- second project tree. Shared nested tables intentionally fail this check: if
-- a caller has aliased live store data, we cannot prove it was not mutated in
-- place and must retain Put's defensive-copy behaviour.
local function DetachedContentEqual(first, second, seen)
    if first == second then return type(first) ~= "table" end
    if type(first) ~= type(second) or type(first) ~= "table" then return false end
    seen = seen or {}
    if seen[first] then return seen[first] == second end
    seen[first] = second
    local count = 0
    for key, value in pairs(first) do
        if not DetachedContentEqual(value, second[key], seen) then return false end
        count = count + 1
    end
    local otherCount = 0
    for _ in pairs(second) do otherCount = otherCount + 1 end
    return count == otherCount
end

local function Utf8Prefix(value, maximumCharacters)
    local text = tostring(value or "")
    local ok, length = pcall(function() return utf8.len(text) end)
    if ok and length then
        if length <= maximumCharacters then return text end
        local offsetOk, offset = pcall(function()
            return utf8.offset(text, maximumCharacters + 1)
        end)
        if offsetOk and offset then return text:sub(1, offset - 1) end
    end
    -- Corrupt legacy byte sequences must not be persisted back to UI labels.
    return text:gsub("[%z\1-\31\127-\255]", "?"):sub(1, maximumCharacters)
end

local function CleanName(value, fallback)
    local name = tostring(value or ""):match("^%s*(.-)%s*$") or ""
    if name == "" then return fallback or "未命名空岛" end
    return Utf8Prefix(name, 28)
end

local function MigrateBuiltinName(name)
    -- Rename only names generated by older releases. User-authored names that
    -- merely contain the old term remain untouched.
    local legacyTerm = "海" .. "岛"
    if name == "我的" .. legacyTerm then return "我的空岛" end
    if name == "未命名" .. legacyTerm then return "未命名空岛" end
    local numbered = name:match("^" .. legacyTerm .. " (%d+)$")
    if numbered then return "空岛 " .. numbered end
    local newNumbered = name:match("^新" .. legacyTerm .. " (%d+)$")
    if newNumbered then return "新空岛 " .. newNumbered end
    return name
end

local function NewId(now, existing)
    existing = existing or {}
    local prefix = "island-" .. tostring(math.max(0, math.floor(tonumber(now) or 0)))
    repeat
        sequence = sequence + 1
        local candidate = prefix .. "-" .. tostring(sequence)
        if not existing[candidate] then return candidate end
    until false
end

local function FindRandomTerrain(collection, terrainId)
    local requested = tostring(terrainId or "")
    for _, record in ipairs(collection and collection.randomTerrains or {}) do
        if tostring(record.id or "") == requested then return record end
    end
    return nil
end

local function TerrainSpec(terrainId, collection)
    local resolved = IslandTerrainCatalog.ResolveId(terrainId)
    local metadata = FindRandomTerrain(collection, resolved)
    return resolved, IslandTerrainCatalog.Get(metadata or resolved) or {}
end

local function TerrainGround(spec)
    return tonumber(spec and spec.groundY) or 0.42
end

local function TerrainCamera(spec)
    local source = type(spec and (spec.camera or spec.defaultCamera)) == "table"
        and (spec.camera or spec.defaultCamera) or {}
    local target = type(source.target) == "table" and source.target or {}
    local overview = type(spec and spec.overview) == "table" and spec.overview or {}
    return {
        theta = tonumber(source.theta) or 0.733,
        phi = tonumber(source.phi) or 0.96,
        radius = tonumber(source.radius) or tonumber(overview.radius) or 118,
        target = {
            tonumber(target[1] or target.x) or tonumber(overview.x) or 0,
            tonumber(target[2] or target.y) or -1.0,
            tonumber(target[3] or target.z) or tonumber(overview.z) or 7,
        },
    }
end

local function NormalizeTerrain(project, fallbackTerrainId, collection)
    local terrain = type(project.terrain) == "table" and project.terrain or {}
    local terrainId, spec = TerrainSpec(
        project.terrainId or terrain.preset or fallbackTerrainId, collection)
    project.terrainId = terrainId
    project.terrain = { preset = terrainId, groundY = TerrainGround(spec) }
    return terrainId, spec
end

local function Project(name, now, terrainId)
    local resolved, spec = TerrainSpec(terrainId)
    return {
        schema = "island-project/v2",
        version = 2,
        revision = 0,
        updatedAt = tonumber(now) or 0,
        name = CleanName(name, "新空岛"),
        terrainId = resolved,
        terrain = { preset = resolved, groundY = TerrainGround(spec) },
        environment = { timeOfDay = 9.5, autoTime = true, dayDuration = 480 },
        instances = {},
        camera = TerrainCamera(spec),
    }
end

local function MigrateLargeArchipelago(project)
    local terrain = type(project.terrain) == "table" and project.terrain or nil
    local sourceTerrainId = project.terrainId or (terrain and terrain.preset)
    if sourceTerrainId ~= "storybook-triple-archipelago" then return end
    local scale = IslandLayout.LEGACY_WORLD_SCALE
    for _, instance in ipairs(project.instances or {}) do
        instance.x = (tonumber(instance.x) or 0) * scale
        instance.z = (tonumber(instance.z) or 0) * scale
    end
    local camera = type(project.camera) == "table" and project.camera or nil
    if camera then
        camera.radius = (tonumber(camera.radius) or 61) * scale
        local target = type(camera.target) == "table" and camera.target or { 0, -1, 3.5 }
        target[1], target[3] = (tonumber(target[1]) or 0) * scale, (tonumber(target[3]) or 3.5) * scale
        camera.target = target
    end
    local terrainId, spec = TerrainSpec(IslandTerrainCatalog.DEFAULT_ID)
    project.terrainId = terrainId
    project.terrain = { preset = terrainId, groundY = TerrainGround(spec) }
end

local function Index(collection)
    local result = {}
    for _, project in ipairs(collection and collection.items or {}) do
        result[tostring(project.islandId)] = project
    end
    return result
end

local function Touch(collection, now)
    collection.revision = (tonumber(collection.revision) or 0) + 1
    collection.updatedAt = tonumber(now) or tonumber(collection.updatedAt) or 0
end

local function NormalizeFlagMap(source)
    local result, count = {}, 0
    for key, value in pairs(type(source) == "table" and source or {}) do
        if value == true and count < 500 then
            result[tostring(key)] = true
            count = count + 1
        end
    end
    return result
end

local function NormalizeRandomTerrains(source, now)
    local result, used = {}, {}
    for index, raw in ipairs(type(source) == "table" and source or {}) do
        if #result >= MAX_RANDOM_TERRAINS then break end
        local record = type(raw) == "table" and raw or { seed = raw }
        local terrainId = tostring(record.id or record.terrainId or "")
        local seed = RandomTerrainGenerator.SeedFromId(terrainId)
        if not seed and record.seed ~= nil then
            seed = RandomTerrainGenerator.NormalizeSeed(record.seed)
            terrainId = RandomTerrainGenerator.IdForSeed(seed)
        end
        if seed then terrainId = RandomTerrainGenerator.IdForSeed(seed) end
        if seed and not used[terrainId] then
            local generated = RandomTerrainGenerator.Generate(seed, { id = terrainId })
            used[terrainId] = true
            result[#result + 1] = {
                id = terrainId,
                seed = seed,
                name = CleanName(record.name, generated.name),
                description = Utf8Prefix(record.description or generated.description, 80),
                algorithm = generated.algorithm,
                algorithmVersion = generated.algorithmVersion,
                formation = generated.formation,
                islandCount = #generated.islands,
                createdAt = tonumber(record.createdAt) or tonumber(record.updatedAt) or now + index * 0.001,
                updatedAt = tonumber(record.updatedAt) or tonumber(record.createdAt) or now + index * 0.001,
            }
        end
    end
    return result, used
end

local function EnsureRandomTerrain(collection, terrainId, now, preferredName)
    if not RandomTerrainGenerator.IsId(terrainId) then return nil end
    local existing = FindRandomTerrain(collection, terrainId)
    if existing then return existing end
    collection.randomTerrains = collection.randomTerrains or {}
    local generated = RandomTerrainGenerator.FromId(terrainId)
    if not generated then return nil end
    local record = {
        id = generated.id,
        seed = generated.seed,
        name = CleanName(preferredName, generated.name),
        description = generated.description,
        algorithm = generated.algorithm,
        algorithmVersion = generated.algorithmVersion,
        formation = generated.formation,
        islandCount = #generated.islands,
        createdAt = tonumber(now) or 0,
        updatedAt = tonumber(now) or 0,
    }
    collection.randomTerrains[#collection.randomTerrains + 1] = record
    return record
end

function IslandProjectStore.Normalize(payload, fallbackProject, now)
    now = tonumber(now) or 0
    local sourceItems, activeId, sourceRandomTerrains
    local rewardUnlockSource = type(payload) == "table" and payload
        or type(fallbackProject) == "table" and fallbackProject or nil
    -- Presence is intentionally different from truthiness here. Once a save
    -- carries rewardUnlocks, even an empty/invalid map is an explicit policy
    -- decision and must not be replaced by migration defaults.
    local hasExplicitRewardUnlocks = type(rewardUnlockSource) == "table"
        and rawget(rewardUnlockSource, "rewardUnlocks") ~= nil
    if type(payload) == "table" and payload.schema == IslandProjectStore.SCHEMA then
        sourceItems, activeId = payload.items or {}, payload.activeId
        sourceRandomTerrains = payload.randomTerrains or payload.customTerrains
    elseif type(payload) == "table" and type(payload.instances) == "table" then
        sourceItems = { payload }
        sourceRandomTerrains = payload.randomTerrains or payload.customTerrains
    elseif type(fallbackProject) == "table" and type(fallbackProject.instances) == "table" then
        sourceItems = { fallbackProject }
        sourceRandomTerrains = fallbackProject.randomTerrains or fallbackProject.customTerrains
    else
        sourceItems = { Project("我的空岛", now) }
    end

    local randomTerrains = NormalizeRandomTerrains(sourceRandomTerrains, now)

    local collection = {
        schema = IslandProjectStore.SCHEMA,
        version = 1,
        revision = type(payload) == "table" and tonumber(payload.revision) or 0,
        updatedAt = type(payload) == "table" and tonumber(payload.updatedAt) or now,
        activeId = activeId and tostring(activeId) or nil,
        marketSyncPending = type(payload) == "table" and payload.marketSyncPending == true,
        exploreFavorites = NormalizeFlagMap(type(payload) == "table" and payload.exploreFavorites),
        exploreLikes = NormalizeFlagMap(type(payload) == "table" and payload.exploreLikes),
        rewardUnlocks = NormalizeFlagMap(rewardUnlockSource and rewardUnlockSource.rewardUnlocks),
        uiDismissals = NormalizeFlagMap(type(payload) == "table" and payload.uiDismissals),
        randomTerrains = randomTerrains,
        items = {},
    }
    local used = {}
    for index, source in ipairs(sourceItems) do
        if type(source) == "table" and type(source.instances) == "table" then
            local project = Copy(source)
            local id = tostring(project.islandId or "")
            if id == "" or used[id] then id = NewId((tonumber(project.updatedAt) or now) + index, used) end
            used[id] = true
            project.islandId = id
            project.name = MigrateBuiltinName(CleanName(project.name,
                index == 1 and "我的空岛" or ("空岛 " .. tostring(index))))
            project.schema, project.version = "island-project/v2", 2
            project.published = project.published == true
            MigrateLargeArchipelago(project)
            NormalizeTerrain(project, nil, collection)
            -- Older saves predate terrain reward gates. Preserve every
            -- non-default terrain already in use so upgrading never locks the
            -- player's current island behind a newly introduced video gate.
            if not hasExplicitRewardUnlocks and project.terrainId ~= IslandTerrainCatalog.DEFAULT_ID then
                collection.rewardUnlocks["terrain:" .. tostring(project.terrainId)] = true
            end
            EnsureRandomTerrain(collection, project.terrainId,
                tonumber(project.updatedAt) or now, project.terrainName)
            collection.items[#collection.items + 1] = project
        end
    end
    if #collection.items == 0 then
        local project = Project("我的空岛", now)
        project.islandId = NewId(now, used)
        collection.items[1] = project
    end
    if not collection.activeId or not used[collection.activeId] then
        collection.activeId = collection.items[1].islandId
    end
    return collection
end

function IslandProjectStore.IsRewardUnlocked(collection, key)
    local cleanKey = tostring(key or ""):match("^%s*(.-)%s*$") or ""
    if cleanKey == "" or type(collection) ~= "table"
        or type(collection.rewardUnlocks) ~= "table" then return false end
    return collection.rewardUnlocks[cleanKey] == true
end

function IslandProjectStore.UnlockReward(collection, key, now)
    if type(collection) ~= "table" then return nil, "空岛数据无效" end
    local cleanKey = tostring(key or ""):match("^%s*(.-)%s*$") or ""
    if cleanKey == "" then return nil, "解锁标识无效" end
    collection.rewardUnlocks = type(collection.rewardUnlocks) == "table"
        and collection.rewardUnlocks or {}
    if collection.rewardUnlocks[cleanKey] == true then return true, false end
    collection.rewardUnlocks[cleanKey] = true
    Touch(collection, now)
    return true, true
end

function IslandProjectStore.IsUIDismissed(collection, key)
    local cleanKey = tostring(key or ""):match("^%s*(.-)%s*$") or ""
    if cleanKey == "" or type(collection) ~= "table"
        or type(collection.uiDismissals) ~= "table" then return false end
    return collection.uiDismissals[cleanKey] == true
end

function IslandProjectStore.DismissUI(collection, key, now)
    if type(collection) ~= "table" then return nil, "空岛数据无效" end
    local cleanKey = tostring(key or ""):match("^%s*(.-)%s*$") or ""
    if cleanKey == "" then return nil, "提示标识无效" end
    collection.uiDismissals = type(collection.uiDismissals) == "table"
        and collection.uiDismissals or {}
    if collection.uiDismissals[cleanKey] == true then return true, false end
    collection.uiDismissals[cleanKey] = true
    Touch(collection, now)
    return true, true
end

function IslandProjectStore.Get(collection, islandId)
    return Index(collection)[tostring(islandId or "")]
end

function IslandProjectStore.GetActive(collection)
    return IslandProjectStore.Get(collection, collection and collection.activeId)
end

function IslandProjectStore.SetActive(collection, islandId, now)
    local project = IslandProjectStore.Get(collection, islandId)
    if not project then return nil, "空岛不存在" end
    collection.activeId = project.islandId
    Touch(collection, now)
    return project
end

function IslandProjectStore.Put(collection, project, now)
    if type(project) ~= "table" or type(project.instances) ~= "table" then return nil, "空岛数据无效" end
    local id = tostring(project.islandId or collection.activeId or "")
    local existing = IslandProjectStore.Get(collection, id)
    if not existing then return nil, "空岛不存在" end
    -- Canonicalize only the small root table first. For the common autosave
    -- case GetProjectData returns a fresh but unchanged tree; comparing it with
    -- the stored project avoids immediately deep-copying the whole snapshot.
    local candidate = {}
    for key, value in pairs(project) do candidate[key] = value end
    candidate.islandId = id
    candidate.name = CleanName(candidate.name, existing.name)
    if project.terrainId == nil then candidate.terrainId = existing.terrainId end
    NormalizeTerrain(candidate, existing.terrainId, collection)
    local hadRandomTerrain = FindRandomTerrain(collection, candidate.terrainId) ~= nil
    local randomTerrain = EnsureRandomTerrain(collection, candidate.terrainId,
        now or candidate.updatedAt)
    local addedRandomTerrain = randomTerrain ~= nil and not hadRandomTerrain
    if project.published == nil then candidate.published = existing.published == true
    else candidate.published = project.published == true end

    local metadataMatches = candidate.revision == existing.revision
        and candidate.updatedAt == existing.updatedAt
    if not addedRandomTerrain and collection.activeId == id and metadataMatches
        and DetachedContentEqual(candidate, existing) then
        return existing
    end

    local copy = Copy(candidate)
    for index, item in ipairs(collection.items) do
        if item.islandId == id then collection.items[index] = copy; break end
    end
    collection.activeId = id
    Touch(collection, now or copy.updatedAt)
    return copy
end

function IslandProjectStore.Create(collection, name, now, terrainId)
    local project = Project(name or ("新空岛 " .. tostring(#collection.items + 1)), now, terrainId)
    EnsureRandomTerrain(collection, project.terrainId, now)
    project.islandId = NewId(now, Index(collection))
    collection.items[#collection.items + 1] = project
    collection.activeId = project.islandId
    Touch(collection, now)
    return project
end

function IslandProjectStore.SetTerrain(collection, islandId, terrainId, now)
    local project = IslandProjectStore.Get(collection, islandId)
    if not project then return nil, "空岛不存在" end
    local resolved, spec = TerrainSpec(terrainId, collection)
    EnsureRandomTerrain(collection, resolved, now)
    project.terrainId = resolved
    project.terrain = { preset = resolved, groundY = TerrainGround(spec) }
    project.camera = TerrainCamera(spec)
    project.revision = (tonumber(project.revision) or 0) + 1
    project.updatedAt = tonumber(now) or project.updatedAt or 0
    Touch(collection, now)
    return project
end

function IslandProjectStore.Duplicate(collection, islandId, now)
    local source = IslandProjectStore.Get(collection, islandId)
    if not source then return nil, "空岛不存在" end
    local project = Copy(source)
    -- A duplicated island may keep portal models as reusable scenery, but it
    -- must never inherit endpoints that still point at the source island's
    -- instance IDs. The copy starts with every portal visibly unbound.
    IslandPortalNetwork.StripProjectBindings(project)
    project.islandId = NewId(now, Index(collection))
    project.name = CleanName(source.name .. " · 副本")
    project.revision = 0
    project.updatedAt = tonumber(now) or 0
    project.published = false
    collection.items[#collection.items + 1] = project
    collection.activeId = project.islandId
    Touch(collection, now)
    return project
end

function IslandProjectStore.Rename(collection, islandId, name, now)
    local project = IslandProjectStore.Get(collection, islandId)
    if not project then return nil, "空岛不存在" end
    local clean = CleanName(name, "")
    if clean == "" then return nil, "空岛名称不能为空" end
    project.name = clean
    project.revision = (tonumber(project.revision) or 0) + 1
    project.updatedAt = tonumber(now) or project.updatedAt or 0
    Touch(collection, now)
    return project
end

function IslandProjectStore.SetPublished(collection, islandId, published, now)
    local project = IslandProjectStore.Get(collection, islandId)
    if not project then return nil, "空岛不存在" end
    project.published = published == true
    project.revision = (tonumber(project.revision) or 0) + 1
    project.updatedAt = tonumber(now) or project.updatedAt or 0
    collection.marketSyncPending = true
    Touch(collection, now)
    return project
end

function IslandProjectStore.Delete(collection, islandId, now)
    if #(collection.items or {}) <= 1 then return nil, "至少保留一座空岛" end
    local deletedIndex
    for index, project in ipairs(collection.items) do
        if project.islandId == tostring(islandId) then deletedIndex = index; break end
    end
    if not deletedIndex then return nil, "空岛不存在" end
    -- Paired portals are one logical connection. Removing an island also
    -- removes every counterpart on surviving islands, including stale one-way
    -- records. Store.Touch below performs the single collection-level revision.
    IslandPortalNetwork.RemoveIslandReferences(
        collection, tostring(islandId), now, { touchCollection = false })
    table.remove(collection.items, deletedIndex)
    if collection.activeId == tostring(islandId) then
        local nextIndex = math.min(deletedIndex, #collection.items)
        collection.activeId = collection.items[nextIndex].islandId
    end
    Touch(collection, now)
    return IslandProjectStore.GetActive(collection)
end

local function RandomTerrainUseCount(collection, terrainId)
    local count = 0
    for _, project in ipairs(collection and collection.items or {}) do
        local projectTerrainId = project.terrainId
            or (type(project.terrain) == "table" and project.terrain.preset)
        if tostring(projectTerrainId or "") == tostring(terrainId or "") then count = count + 1 end
    end
    return count
end

function IslandProjectStore.GetRandomTerrain(collection, terrainId)
    local record = FindRandomTerrain(collection, terrainId)
    return record and Copy(record) or nil
end

function IslandProjectStore.ListRandomTerrains(collection)
    local result = {}
    local active = IslandProjectStore.GetActive(collection)
    for _, record in ipairs(collection and collection.randomTerrains or {}) do
        local islandCount = tonumber(record.islandCount)
        local formation = record.formation
        local spec
        if not islandCount or not formation then
            spec = IslandTerrainCatalog.Get(record)
            islandCount = spec and #spec.islands or 0
            formation = spec and spec.formation or nil
        end
        if RandomTerrainGenerator.IsId(record.id) then
            result[#result + 1] = {
                id = record.id,
                name = record.name,
                description = record.description or (spec and spec.description),
                seed = record.seed,
                algorithm = record.algorithm or (spec and spec.algorithm),
                algorithmVersion = record.algorithmVersion or (spec and spec.algorithmVersion),
                formation = formation,
                islandCount = islandCount,
                inUseCount = RandomTerrainUseCount(collection, record.id),
                active = active and active.terrainId == record.id or false,
                createdAt = tonumber(record.createdAt) or 0,
                updatedAt = tonumber(record.updatedAt) or 0,
            }
        end
    end
    table.sort(result, function(first, second)
        if first.updatedAt ~= second.updatedAt then return first.updatedAt > second.updatedAt end
        return tostring(first.name) < tostring(second.name)
    end)
    return result
end

function IslandProjectStore.CreateRandomTerrain(collection, name, seed, now)
    if type(collection) ~= "table" then return nil, "空岛数据无效" end
    collection.randomTerrains = collection.randomTerrains or {}

    local explicitSeed = seed ~= nil
    randomSequence = randomSequence + 1
    local normalized = explicitSeed and RandomTerrainGenerator.NormalizeSeed(seed)
        or RandomTerrainGenerator.NormalizeSeed(table.concat({
            "terrain", tostring(now or 0), tostring(collection.revision or 0),
            tostring(#collection.randomTerrains), tostring(randomSequence),
        }, ":"))
    local terrainId = RandomTerrainGenerator.IdForSeed(normalized)
    local existing = FindRandomTerrain(collection, terrainId)
    if existing and explicitSeed then return Copy(existing) end
    if #collection.randomTerrains >= MAX_RANDOM_TERRAINS then
        return nil, "随机地形最多保留 " .. tostring(MAX_RANDOM_TERRAINS) .. " 个"
    end
    while existing do
        normalized = RandomTerrainGenerator.NormalizeSeed(
            tostring(normalized) .. ":" .. tostring(randomSequence))
        terrainId = RandomTerrainGenerator.IdForSeed(normalized)
        existing = FindRandomTerrain(collection, terrainId)
        randomSequence = randomSequence + 1
    end

    local generated = RandomTerrainGenerator.Generate(normalized, { id = terrainId })
    local record = {
        id = terrainId,
        seed = normalized,
        name = CleanName(name, "随机地形 " .. tostring(#collection.randomTerrains + 1)),
        description = generated.description,
        algorithm = generated.algorithm,
        algorithmVersion = generated.algorithmVersion,
        formation = generated.formation,
        islandCount = #generated.islands,
        createdAt = tonumber(now) or 0,
        updatedAt = tonumber(now) or 0,
    }
    collection.randomTerrains[#collection.randomTerrains + 1] = record
    Touch(collection, now)
    return Copy(record)
end

function IslandProjectStore.RenameRandomTerrain(collection, terrainId, name, now)
    local record = FindRandomTerrain(collection, terrainId)
    if not record then return nil, "随机地形不存在" end
    local clean = CleanName(name, "")
    if clean == "" then return nil, "地形名称不能为空" end
    record.name = clean
    record.updatedAt = tonumber(now) or record.updatedAt or 0
    Touch(collection, now)
    return Copy(record)
end

function IslandProjectStore.RegenerateRandomTerrain(collection, terrainId, newSeed, now)
    local record = FindRandomTerrain(collection, terrainId)
    if not record then return nil, "随机地形不存在" end
    local inUse = RandomTerrainUseCount(collection, record.id)
    if inUse > 0 then
        return nil, "该地形正被 " .. tostring(inUse) .. " 座空岛使用，请先切换这些空岛的地形"
    end
    local explicitSeed = newSeed ~= nil
    randomSequence = randomSequence + 1
    local normalized = explicitSeed and RandomTerrainGenerator.NormalizeSeed(newSeed)
        or RandomTerrainGenerator.NormalizeSeed(table.concat({
            "regenerate", tostring(record.seed), tostring(now or 0), tostring(randomSequence),
        }, ":"))
    local nextId = RandomTerrainGenerator.IdForSeed(normalized)
    if nextId == record.id then return nil, "新种子与当前地形相同" end
    local duplicate = FindRandomTerrain(collection, nextId)
    if duplicate then
        if explicitSeed then return nil, "这个种子已经生成过了" end
        repeat
            randomSequence = randomSequence + 1
            normalized = RandomTerrainGenerator.NormalizeSeed(
                tostring(normalized) .. ":" .. tostring(randomSequence))
            nextId = RandomTerrainGenerator.IdForSeed(normalized)
            duplicate = FindRandomTerrain(collection, nextId)
        until not duplicate
    end

    local generated = RandomTerrainGenerator.Generate(normalized, { id = nextId, name = record.name })
    record.id = nextId
    record.seed = normalized
    record.description = generated.description
    record.algorithm = generated.algorithm
    record.algorithmVersion = generated.algorithmVersion
    record.formation = generated.formation
    record.islandCount = #generated.islands
    record.updatedAt = tonumber(now) or record.updatedAt or 0
    Touch(collection, now)
    return Copy(record)
end

function IslandProjectStore.DeleteRandomTerrain(collection, terrainId, now, options)
    options = type(options) == "table" and options or {}
    local deletedIndex, record
    for index, candidate in ipairs(collection and collection.randomTerrains or {}) do
        if tostring(candidate.id or "") == tostring(terrainId or "") then
            deletedIndex, record = index, candidate
            break
        end
    end
    if not deletedIndex then return nil, "随机地形不存在" end
    local inUse = RandomTerrainUseCount(collection, record.id)
    if inUse > 0 and not options.force then
        return nil, "该地形正被 " .. tostring(inUse) .. " 座空岛使用"
    end
    if inUse > 0 then
        local defaultId, defaultSpec = TerrainSpec(IslandTerrainCatalog.DEFAULT_ID, collection)
        for _, project in ipairs(collection.items or {}) do
            if tostring(project.terrainId or "") == record.id then
                project.terrainId = defaultId
                project.terrain = { preset = defaultId, groundY = TerrainGround(defaultSpec) }
                project.camera = TerrainCamera(defaultSpec)
                project.revision = (tonumber(project.revision) or 0) + 1
                project.updatedAt = tonumber(now) or project.updatedAt or 0
            end
        end
    end
    table.remove(collection.randomTerrains, deletedIndex)
    Touch(collection, now)
    return true, inUse
end

function IslandProjectStore.Summaries(collection)
    local result = {}
    for _, project in ipairs(collection and collection.items or {}) do
        local terrainId, terrainSpec = TerrainSpec(project.terrainId
            or (type(project.terrain) == "table" and project.terrain.preset), collection)
        result[#result + 1] = {
            id = project.islandId,
            name = project.name,
            terrainId = terrainId,
            terrainName = tostring(terrainSpec.name or "经典三岛"),
            count = #(project.instances or {}),
            updatedAt = tonumber(project.updatedAt) or 0,
            active = project.islandId == collection.activeId,
            published = project.published == true,
        }
    end
    table.sort(result, function(a, b)
        if a.active ~= b.active then return a.active end
        if a.updatedAt ~= b.updatedAt then return a.updatedAt > b.updatedAt end
        return tostring(a.name) < tostring(b.name)
    end)
    return result
end

return IslandProjectStore
